server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-account-db
    username: postgres
    password: satyam
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51S4lmw9ddI7TTPGG5gfHOIOTUvMhRk9s1Fd3zvYq8UNfvwPKZEyKnjI8o026uAeTFmjT3p3n7lucdZ1JKO9iCdiW008ajVypEZ
  webhook:
    secret: whsec_1f2beb298b67fc1da93c54082fce1b10a7ecd7f2e09674f3b7e14f646393f1bc

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/account_db
    username: account_user
    password: ${DB_PASSWORD}


stripe:
  api:
    secret: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
