server:
  port: 9030
  servlet:
    context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-intelligence-db
    username: postgres
    password: satyam
    driver-class-name: org.postgresql.Driver

  ai:
    model:
      chat: google-genai

    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.2

---

spring:
  config:
    activate:
      on-profile: k8s

  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}

  ai:
    model:
      chat: google-genai

    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.2
